### ISSUE TITLE
receive QR code generating not necessary information

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/electrum-komodo#21]
QR code encodes information `komodo:walletaddress` instead of just `walletaddress` so when scan this code in another app - not valid information input

![image](https://user-images.githubusercontent.com/24797699/63786756-d917e580-c91c-11e9-8311-220ecbc2ef19.png)

![image](https://user-images.githubusercontent.com/24797699/63786795-f2b92d00-c91c-11e9-9140-57e1aa4e7828.png)

![image](https://user-images.githubusercontent.com/24797699/63786818-f947a480-c91c-11e9-9bac-45d3caccfdd2.png)

**Comment by pbca26** [comment]
this is a standard bitcoin url scheme https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki#simpler-syntax

**Comment by tonymorony** [comment]
I see, thank you for clarification! So it should be pruned on atomicdex (QR receiver) side I think
